# Generated by Django 4.2.30 on 2026-09-30 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable trigger name (e.g. Login, Logout)', max_length=100)),
                ('slug', models.SlugField(help_text='Unique slug for code triggering (e.g. login, logout)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of when this trigger fires')),
                ('is_active', models.BooleanField(default=True, help_text='Master active toggle for this trigger')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='+1234567890', max_length=30)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('web_push', 'Web Push')], max_length=20)),
                ('recipient', models.CharField(help_text='Phone number, email address, or browser push endpoint', max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent Successfully'), ('failed', 'Delivery Failed'), ('simulated', 'Simulated (Sandbox/Mock)'), ('skipped', 'Skipped (Channel Disabled)')], max_length=20)),
                ('service_response', models.JSONField(blank=True, default=dict, help_text='Provider API response or error trace')),
                ('is_test', models.BooleanField(default=False, help_text='Whether this was triggered via Test Send button')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.trigger')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('web_push', 'Web Push')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True, help_text='Toggle channel ON or OFF for this trigger')),
                ('title', models.CharField(blank=True, help_text='Email Subject, Web Push Title, or WhatsApp Template Header', max_length=255)),
                ('body', models.TextField(help_text='Message body. Supports variables like {{username}}, {{email}}, {{time}}, etc.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('active', 'Active')], default='approved', max_length=30)),
                ('meta_template_name', models.CharField(blank=True, help_text='Meta WhatsApp template name if synced', max_length=100)),
                ('variables_schema', models.JSONField(blank=True, default=list, help_text='List of supported variables')),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='Extra settings e.g. icon URL, target URL for Web Push, button action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='notifications.trigger')),
            ],
            options={
                'ordering': ['trigger_id', 'channel'],
                'unique_together': {('trigger', 'channel')},
            },
        ),
    ]
